name: Deploy OU Class Manager Backend

on:
  push:
    branches: [ main ]
    paths: [ 'backend/**' ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create Firebase Service Account File
      run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > backend/firebase-service-account.json

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and Push Container
      run: |
        docker build -t us-central1-docker.pkg.dev/soonerflow/soonerflow-backend/backend .
        docker push us-central1-docker.pkg.dev/soonerflow/soonerflow-backend/backend

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy soonerflow-backend \
          --image=us-central1-docker.pkg.dev/soonerflow/soonerflow-backend/backend \
          --region=us-central1 \
          --allow-unauthenticated \
          --set-env-vars=LOG_LEVEL=INFO \
          --set-secrets=DATABASE_URL=DATABASE_URL:latest \
          --add-cloudsql-instances=soonerflow:us-central1:soonerflow \
          --memory=1Gi \
          --cpu=1 \
          --min-instances=1 \
          --max-instances=10